---
apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: fbc-standard
  namespace: rhbk-release-tenant
spec:
  configuration:
    include:
      - '@redhat'
    exclude:
      # The release process separates the catalog from the binaries,
      # so CVEs are the responsibility of the OLM team
      - cve
      - step_image_registries
      # prefetch is not required
      - tasks.required_tasks_found:prefetch-dependencies
      # source containers are not required
      - tasks.required_tasks_found:source-build
      # summary being skipped due to missing task parameter from source build
      # since source builds are skipped
      - tasks.required_tasks_found:summary
  description: 'Includes rules for shipping Red Hat FBC fragments'
  publicKey: 'k8s://openshift-pipelines/public-key'
  sources:
    - name: Release Policies
      data:
        - github.com/release-engineering/rhtap-ec-policy//data
        - oci::quay.io/redhat-appstudio-tekton-catalog/data-acceptable-bundles:latest
      policy:
        - oci::quay.io/enterprise-contract/ec-release-policy:latest