apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  name: rhbk-release-v4-14-enterprise-contract
  namespace: rhtap-release-2-tenant
  labels:
    test.appstudio.openshift.io/optional: 'false'
spec:
  application: rhbk-release-v4-14
  contexts:
    - description: Application testing
      name: application
  params:
    - name: POLICY_CONFIGURATION
      value: rhtap-release-2-tenant/fbc-standard
  resolverRef:
    params:
      - name: url
        value: 'https://github.com/redhat-appstudio/build-definitions'
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/enterprise-contract-redhat.yaml
    resolver: git
